color = input("Introduce un color ")
materia = input("Introduce una materia ")
verbo = input("Introduce un verbo ")
alimento = input("Introduce un alimento")
nombre_mujer = input("Introduce un nombre de mujer ")
nombre_hombre = input("Introduce un nombre de hombre ")

print("Cuando entré a la universidad, me voy a comprar un abrigo " + color + " para ir a la clase de " + materia)
print("Luego de " + verbo + " iré a la cafetería a comer un " + alimento + ". Me veré con mi amiga " + nombre_mujer)
print("y hablaremos acerca de   " + nombre_hombre)